const mdnDicWords18934 = [
  ["aback", "shafqatsiz"],
  ["abaft", "abaft"],
  ["abandoned", "tark etildi"],
  ["abashed", "g'azablandi"],
  ["aberrant", "aberrant"],
  ["abhorrent", "jirkanch"],
  ["abiding", "davom etmoqda"],
  ["abject", "yo'qotish"],
  ["ablaze", "yong'in"],
  ["able", "qodir"],
  ["abnormal", "anormal"],
  ["aboard", "kemada"],
  ["aboriginal", "aboriginal"],
  ["abortive", "bekor qilish"],
  ["abounding", "juda ko'p"],
  ["abrasive", "aşındırıcı"],
  ["abrupt", "keskin"],
  ["absent", "yo'q"],
  ["absorbed", "so'riladi"],
  ["absorbing", "changni yutish"],
  ["abstracted", "ajratib olingan"],
  ["absurd", "absurd"],
  ["abundant", "mo'l"],
  ["abusive", "tajovuzkor"],
  ["acceptable", "qabul qilinadi"],
  ["accessible", "foydalanish mumkin"],
  ["accidental", "tasodifiy"],
  ["accurate", "aniq"],
  ["acid", "kislota"],
  ["acidic", "kislotali"],
  ["acoustic", "akustik"],
  ["acrid", "akrid"],
  ["actually", "aslida"],
  ["ad hoc", "maxsus"],
  ["adamant", "qat'iy"],
  ["adaptable", "moslashuvchan"],
  ["addicted", "odatdagidek"],
  ["adhesive", "yopishtiruvchi"],
  ["adjoining", "qo'shni"],
  ["adorable", "yoqimli"],
  ["adventurous", "sarguzasht"],
  ["afraid", "qo'rqaman"],
  ["aggressive", "tajovuzkor"],
  ["agonizing", "zo'ravonlik"],
  ["agreeable", "yoqimli"],
  ["ahead", "oldinga"],
  ["ajar", "ajar"],
  ["alcoholic", "spirtli"],
  ["alert", "ogohlantirish"],
  ["alike", "shunga o'xshash"],
  ["alive", "tirik"],
  ["alleged", "da'vo qilingan"],
  ["alluring", "jozibali"],
  ["aloof", "aloof"],
  ["amazing", "ajoyib"],
  ["ambiguous", "noaniq"],
  ["ambitious", "ehtirosli"],
  ["amuck", "amuk"],
  ["amused", "qiziqarli"],
  ["amusing", "qiziqarli"],
  ["ancient", "qadimgi"],
  ["angry", "badjahl"],
  ["animated", "jonlantirilgan"],
  ["annoyed", "bezovta"],
  ["annoying", "zerikarli"],
  ["anxious", "tashvishli"],
  ["apathetic", "befarq"],
  ["aquatic", "suv"],
  ["aromatic", "aromatik"],
  ["arrogant", "dimog'dor"],
  ["ashamed", "uyaldi"],
  ["aspiring", "istaganlar"],
  ["assorted", "turli xil"],
  ["astonishing", "ajablanarli"],
  ["attractive", "jozibali"],
  ["auspicious", "xayrli"],
  ["automatic", "avtomatik"],
  ["available", "mavjud"],
  ["average", "o'rtacha"],
  ["awake", "uyg'oq"],
  ["aware", "xabardor"],
  ["awesome", "dahshatli"],
  ["awful", "dahshatli"],
  ["axiomatic", "aksiomatik"],
  ["bad", "yomon"],
  ["barbarous", "barbar"],
  ["bashful", "uyatli"],
  ["bawdy", "bavdy"],
  ["beautiful", "chiroyli"],
  ["befitting", "yoqimli"],
  ["belligerent", "urushqoq odam"],
  ["beneficial", "foydali"],
  ["bent", "egilgan"],
  ["berserk", "berserk"],
  ["best", "eng yaxshisi"],
  ["better", "yaxshiroq"],
  ["bewildered", "hayratda qoldilar"],
  ["big", "katta"],
  ["billowy", "billowy"],
  ["bite-sized", "luqma-o'lchovli"],
  ["bitter", "achchiq"],
  ["bizarre", "g'alati"],
  ["black", "qora"],
  ["black-and-white", "qora va oq"],
  ["bloody", "qonli"],
  ["blue", "ko'k"],
  ["blue-eyed", "ko'k ko'zli"],
  ["blushing", "blushing"],
  ["boiling", "qaynatish"],
  ["boorish", "sharmandalik"],
  ["bored", "zerikdi"],
  ["boring", "zerikarli"],
  ["bouncy", "bouncy"],
  ["boundless", "cheksiz"],
  ["brainy", "aqlli"],
  ["brash", "shafqatsizlik"],
  ["brave", "jasur"],
  ["brawny", "qoshiq"],
  ["breakable", "breakable"],
  ["breezy", "shamol"],
  ["brief", "qisqacha"],
  ["bright", "yorqin"],
  ["bright", "yorqin"],
  ["broad", "keng"],
  ["broken", "singan"],
  ["brown", "jigarrang"],
  ["bumpy", "jirkanch"],
  ["burly", "burly"],
  ["bustling", "harakatlanuvchi"],
  ["busy", "band"],
  ["cagey", "kagay"],
  ["calculating", "hisoblash"],
  ["callous", "shafqatsiz"],
  ["calm", "sokin"],
  ["capable", "qodir"],
  ["capricious", "shijoatli"],
  ["careful", "ehtiyot bo'ling"],
  ["careless", "ehtiyotsiz"],
  ["caring", "g'amxo'rlik qilish"],
  ["cautious", "ehtiyotkorlik bilan"],
  ["ceaseless", "to'xtovsiz"],
  ["certain", "aniq"],
  ["changeable", "o'zgarishi mumkin"],
  ["charming", "maftunkor"],
  ["cheap", "arzon"],
  ["cheerful", "quvnoq"],
  ["chemical", "kimyoviy moddalar"],
  ["chief", "boshlig'i"],
  ["childlike", "bolalik kabi"],
  ["chilly", "sovuq"],
  ["chivalrous", "chavandoz"],
  ["chubby", "tombul"],
  ["chunky", "chunky"],
  ["clammy", "jingalak"],
  ["classy", "mumtoz"],
  ["clean", "toza"],
  ["clear", "aniq"],
  ["clever", "aqlli"],
  ["cloistered", "monastir"],
  ["cloudy", "bulutli"],
  ["closed", "yopiq"],
  ["clumsy", "jirkanch"],
  ["cluttered", "chalkash"],
  ["coherent", "izchil"],
  ["cold", "sovuq"],
  ["colorful", "rangli"],
  ["colossal", "ulkan"],
  ["combative", "jangchi"],
  ["comfortable", "qulay"],
  ["common", "umumiy"],
  ["complete", "to'liq"],
  ["complex", "murakkab"],
  ["concerned", "manfaatdor"],
  ["condemned", "hukm qilindi"],
  ["confused", "aralashdi"],
  ["conscious", "ongli"],
  ["cooing", "kuyikish"],
  ["cool", "salqin"],
  ["cooperative", "hamkorlik"],
  ["coordinated", "muvofiqlashtirildi"],
  ["courageous", "jasur"],
  ["cowardly", "qo'rqoqlik bilan"],
  ["crabby", "Qisqichbaqa"],
  ["craven", "jasur"],
  ["crazy", "aqldan"],
  ["creepy", "shilimshiq"],
  ["crooked", "buzilgan"],
  ["crowded", "olomon"],
  ["cruel", "shafqatsiz"],
  ["cuddly", "jozibali"],
  ["cultured", "madaniyatga ega"],
  ["cumbersome", "noqulay"],
  ["curious", "qiziq"],
  ["curly", "jingalak"],
  ["curved", "kavisli"],
  ["curvy", "egri"],
  ["cut", "kesish"],
  ["cute", "yoqimli"],
  ["cute", "yoqimli"],
  ["cynical", "kinoyali"],
  ["daffy", "daffy"],
  ["daily", "har kuni"],
  ["damaged", "zarar etkazilgan"],
  ["damaging", "zarar etkazishi mumkin"],
  ["damp", "namlik"],
  ["dangerous", "xavfli"],
  ["dapper", "dapper"],
  ["dark", "qorong'i"],
  ["dashing", "chaqqonlik"],
  ["dazzling", "ko'zni qamashtiradigan"],
  ["dead", "o'lik"],
  ["deadpan", "o'lik"],
  ["deafening", "quloq solar"],
  ["dear", "azizim"],
  ["debonair", "debonair"],
  ["decisive", "hal qiluvchi ahamiyatga ega"],
  ["decorous", "bezaksiz"],
  ["deep", "chuqur"],
  ["deeply", "chuqur"],
  ["defeated", "mag'lub bo'ldi"],
  ["defective", "nomukammal"],
  ["defiant", "qarshi"],
  ["delicate", "nozik"],
  ["delicious", "mazali"],
  ["delightful", "yoqimli"],
  ["demonic", "iblisdir"],
  ["delirious", "jozibali"],
  ["dependent", "qaram"],
  ["depressed", "tushkunlikka tushgan"],
  ["deranged", "buzilgan"],
  ["descriptive", "tavsiflovchi"],
  ["deserted", "ketgan"],
  ["detailed", "batafsil"],
  ["determined", "aniqlandi"],
  ["devilish", "iblis"],
  ["didactic", "didaktik"],
  ["different", "turli xil"],
  ["difficult", "qiyin"],
  ["diligent", "mehnatsevar"],
  ["direful", "qo'rqinchli"],
  ["dirty", "iflos"],
  ["disagreeable", "noqulay"],
  ["disastrous", "falokat"],
  ["discreet", "ehtiyotkorlik bilan"],
  ["disgusted", "nafratlangan"],
  ["disgusting", "jirkanch"],
  ["disillusioned", "xafa bo'ldi"],
  ["dispensable", "tarqatish mumkin"],
  ["distinct", "farq qiladi"],
  ["disturbed", "buzilgan"],
  ["divergent", "turli xil"],
  ["dizzy", "Bosh aylanishi"],
  ["domineering", "hukmronlik qilish"],
  ["doubtful", "shubhali"],
  ["drab", "tortishish"],
  ["draconian", "Drachen"],
  ["dramatic", "dramatik"],
  ["dreary", "xavfli"],
  ["drunk", "mast"],
  ["dry", "quruq"],
  ["dull", "zerikarli"],
  ["dusty", "chang bosgan"],
  ["dusty", "chang bosgan"],
  ["dynamic", "dinamik"],
  ["dysfunctional", "ishsiz"],
  ["eager", "istak"],
  ["early", "erta"],
  ["earsplitting", "eshitish"],
  ["earthy", "tuproq"],
  ["easy", "oson"],
  ["eatable", "ovqatlanish mumkin"],
  ["economic", "iqtisodiy"],
  ["educated", "o'qimishli"],
  ["efficacious", "ta'sirchan"],
  ["efficient", "samarali"],
  ["eight", "sakkizta"],
  ["elastic", "elastik"],
  ["elated", "qiziquvchan"],
  ["elderly", "yoshi katta"],
  ["electric", "elektr"],
  ["elegant", "oqlangan"],
  ["elfin", "elfin"],
  ["elite", "elita"],
  ["embarrassed", "xijolat tortdi"],
  ["eminent", "taniqli"],
  ["empty", "bo'sh"],
  ["enchanted", "sehrlangan"],
  ["enchanting", "sehrlangan"],
  ["encouraging", "rag'batlantiruvchi"],
  ["endurable", "chidamli"],
  ["energetic", "energetik"],
  ["enormous", "ulkan"],
  ["entertaining", "qiziqarli"],
  ["enthusiastic", "g'ayratli"],
  ["envious", "g'azablangan"],
  ["equable", "teng"],
  ["equal", "teng"],
  ["erect", "ko'tarmoq"],
  ["erratic", "noto'g'ri"],
  ["ethereal", "ethereal"],
  ["evanescent", "evangelist"],
  ["evasive", "evakuatsiya"],
  ["even", "hatto"],
  ["excellent", "juda yaxshi"],
  ["excited", "hayajonlangan"],
  ["exciting", "hayajonli"],
  ["exclusive", "eksklyuziv"],
  ["exotic", "ekzotik"],
  ["expensive", "qimmat"],
  ["extra-large", "juda katta"],
  ["extra-small", "juda kichik"],
  ["exuberant", "jozibali"],
  ["exultant", "mamnuniyat bilan"],
  ["fabulous", "ajoyib"],
  ["faded", "nafas oldi"],
  ["faint", "holsiz"],
  ["fair", "adolatli"],
  ["faithful", "ishonchli"],
  ["fallacious", "noto'g'ri"],
  ["false", "noto'g'ri"],
  ["familiar", "tanish"],
  ["famous", "mashhur"],
  ["fanatical", "fanatik"],
  ["fancy", "farasingiz"],
  ["fantastic", "hayoliy"],
  ["far", "uzoq"],
  ["far-flung", "juda uzoqqa cho'zilgan"],
  ["fascinated", "hayratga tushdi"],
  ["fast", "tez"],
  ["fat", "yog '"],
  ["faulty", "noto'g'ri"],
  ["fearful", "qo'rqinchli"],
  ["fearless", "qo'rqmasdan"],
  ["feeble", "zaif"],
  ["feigned", "ifodalangan"],
  ["female", "ayol"],
  ["fertile", "unumdor"],
  ["festive", "bayram"],
  ["few", "ozchilik"],
  ["fierce", "shafqatsiz"],
  ["filthy", "iflos"],
  ["fine", "yaxshi"],
  ["finicky", "nozik"],
  ["first", "birinchi bo'lib"],
  ["five", "beshta"],
  ["fixed", "qattiq"],
  ["flagrant", "shafqatsiz"],
  ["flaky", "po'stloq"],
  ["flashy", "jozibali"],
  ["flat", "tekis"],
  ["flawless", "mukammal"],
  ["flimsy", "noqulay"],
  ["flippant", "flippant"],
  ["flowery", "gullar"],
  ["fluffy", "yumshoq"],
  ["fluttering", "fluttering"],
  ["foamy", "ko'pikli"],
  ["foolish", "ahmoqona"],
  ["foregoing", "yuqorida keltirilgan"],
  ["forgetful", "unutuvchan"],
  ["fortunate", "baxtli"],
  ["four", "to'rtta"],
  ["frail", "zaif"],
  ["fragile", "nozik"],
  ["frantic", "shafqatsiz"],
  ["free", "ozod"],
  ["freezing", "muzlatish"],
  ["frequent", "tez-tez"],
  ["fresh", "yangi"],
  ["fretful", "noqulay"],
  ["friendly", "do'stona"],
  ["frightened", "qo'rqib ketdi"],
  ["frightening", "qo'rqinchli"],
  ["full", "to'liq"],
  ["fumbling", "tirilish"],
  ["functional", "funktsional"],
  ["funny", "kulgili"],
  ["furry", "mo'yna"],
  ["furtive", "furtive"],
  ["future", "kelajak"],
  ["futuristic", "futuristik"],
  ["fuzzy", "loyqa"],
  ["gabby", "gabby"],
  ["gainful", "foydasiz"],
  ["gamy", "gamy"],
  ["gaping", "gapirish"],
  ["garrulous", "garrulous"],
  ["gaudy", "gaudy"],
  ["general", "umumiy"],
  ["gentle", "muloyim"],
  ["giant", "ulkan"],
  ["giddy", "moyillik"],
  ["gifted", "iqtidorli"],
  ["gigantic", "ulkan"],
  ["glamorous", "jozibali"],
  ["gleaming", "gullab-yashnamoqda"],
  ["glib", "glib"],
  ["glistening", "porlash"],
  ["glorious", "ajoyib"],
  ["glossy", "porloq"],
  ["godly", "xudojo'y"],
  ["good", "yaxshi"],
  ["goofy", "goofy"],
  ["gorgeous", "ajoyib"],
  ["graceful", "oqlangan"],
  ["grandiose", "ulkan"],
  ["grateful", "minnatdor"],
  ["gratis", "bepul"],
  ["gray", "kulrang"],
  ["greasy", "yog'li"],
  ["great", "ajoyib"],
  ["greedy", "ochko'z"],
  ["green", "yashil rangda"],
  ["grey", "kulrang"],
  ["grieving", "xafa"],
  ["groovy", "groovy"],
  ["grotesque", "kulgili"],
  ["grouchy", "g'amxo'rlik"],
  ["grubby", "iflos"],
  ["gruesome", "qo'rqinchli"],
  ["grumpy", "xira"],
  ["guarded", "himoyalangan"],
  ["guiltless", "aybdor emas"],
  ["gullible", "ishonchli"],
  ["gusty", "zerikarli"],
  ["guttural", "guttural"],
  ["habitual", "odatiy"],
  ["half", "yarim"],
  ["hallowed", "muqaddas qildi"],
  ["halting", "to'xtatish"],
  ["handsome", "kelishgan"],
  ["handsomely", "chiroyli"],
  ["handy", "foydalanishga"],
  ["hanging", "osilgan"],
  ["hapless", "bema'nilik"],
  ["happy", "baxtli"],
  ["hard", "qiyin"],
  ["hard-to-find", "qiyin topish"],
  ["harmonious", "uyg'un"],
  ["harsh", "qattiq"],
  ["hateful", "nafratlangan"],
  ["heady", "boshli"],
  ["healthy", "sog'lom"],
  ["heartbreaking", "yurak urishi"],
  ["heavenly", "samoviy"],
  ["heavy", "og'ir"],
  ["hellish", "do'zax"],
  ["helpful", "foydali"],
  ["helpless", "yordamsiz"],
  ["hesitant", "ikkilanmasdan"],
  ["hideous", "yoqimsiz"],
  ["high", "yuqori"],
  ["highfalutin", "yuqorifalutin"],
  ["high-pitched", "yuqori pitched"],
  ["hilarious", "xushchaqchaq"],
  ["hissing", "tishlash"],
  ["historical", "tarixiy"],
  ["holistic", "yaxlit"],
  ["hollow", "ichi bo'sh"],
  ["homeless", "uysiz"],
  ["homely", "uyqusiz"],
  ["honorable", "sharafli"],
  ["horrible", "dahshatli"],
  ["hospitable", "mehmondo'st"],
  ["hot", "issiq"],
  ["huge", "katta"],
  ["hulking", "hulking"],
  ["humdrum", "jigarrang"],
  ["humorous", "kulgili"],
  ["hungry", "ochlik"],
  ["hurried", "tezda"],
  ["hurt", "jarohatlar"],
  ["hushed", "chirindi"],
  ["husky", "husky"],
  ["hypnotic", "gipnoz"],
  ["hysterical", "histerik"],
  ["icky", "icky"],
  ["icy", "muzli"],
  ["idiotic", "ahmoqona"],
  ["ignorant", "johil"],
  ["ill", "kasal"],
  ["illegal", "noqonuniy"],
  ["ill-fated", "yomon niyatli"],
  ["ill-informed", "noto'g'ri ma'lumot"],
  ["illustrious", "mashhur"],
  ["imaginary", "xayoliy"],
  ["immense", "ulkan"],
  ["imminent", "yaqin"],
  ["impartial", "xolis"],
  ["imperfect", "nomukammal"],
  ["impolite", "qo'pol"],
  ["important", "muhim"],
  ["imported", "import qilingan"],
  ["impossible", "mumkin emas"],
  ["incandescent", "akkor"],
  ["incompetent", "qobiliyatsiz"],
  ["inconclusive", "noaniq"],
  ["industrious", "mehnatkash"],
  ["incredible", "ajoyib"],
  ["inexpensive", "arzon"],
  ["infamous", "sharmandali"],
  ["innate", "tug'ma"],
  ["innocent", "begunoh"],
  ["inquisitive", "qiziquvchan"],
  ["insidious", "hiyla bilan"],
  ["instinctive", "instinktiv"],
  ["intelligent", "aqlli"],
  ["interesting", "qiziqarli"],
  ["internal", "ichki"],
  ["invincible", "yengilmas"],
  ["irate", "irate"],
  ["irritating", "bezovta qilmoqda"],
  ["itchy", "qichiydigan"],
  ["jaded", "yigitlar"],
  ["jagged", "jagged"],
  ["jazzy", "jazy"],
  ["jealous", "rashkchi"],
  ["jittery", "jittery"],
  ["jobless", "ishsiz"],
  ["jolly", "jolly"],
  ["joyous", "quvonchli"],
  ["judicious", "aqlli"],
  ["juicy", "suvli"],
  ["jumbled", "jim bo'ldi"],
  ["jumpy", "jumpy"],
  ["juvenile", "balog'atga etmagan bola"],
  ["kaput", "kaput"],
  ["keen", "o'tkir"],
  ["kind", "mehribon"],
  ["kindhearted", "mehr-muhabbatli"],
  ["kindly", "muloyimlik bilan"],
  ["knotty", "tuguncha"],
  ["knowing", "bilish"],
  ["knowledgeable", "bilimdon"],
  ["known", "ma'lum"],
  ["labored", "mehnat qildi"],
  ["lackadaisical", "yo'qolgan"],
  ["lacking", "yo'q"],
  ["lame", "cho'loq"],
  ["lamentable", "mudhish"],
  ["languid", "noqulay"],
  ["large", "katta"],
  ["last", "oxirgi"],
  ["late", "kech"],
  ["laughable", "kulgili"],
  ["lavish", "juda boy"],
  ["lazy", "dangasa"],
  ["lean", "arzimagan"],
  ["learned", "bilib oldim"],
  ["left", "chapda"],
  ["legal", "qonuniy"],
  ["lethal", "o'lik"],
  ["level", "Daraja"],
  ["lewd", "levd"],
  ["light", "yorug'lik"],
  ["like", "kabi"],
  ["likeable", "yoqimli"],
  ["limping", "nafas olish"],
  ["literate", "savodli"],
  ["little", "biroz"],
  ["lively", "jonli"],
  ["lively", "jonli"],
  ["living", "yashash"],
  ["lonely", "yolg'iz"],
  ["long", "uzoq"],
  ["longing", "hushyorlik"],
  ["long-term", "Uzoq muddat"],
  ["loose", "bo'shashmasdan"],
  ["lopsided", "lopsided"],
  ["loud", "baland ovozda"],
  ["loutish", "loutish"],
  ["lovely", "yaxshi"],
  ["loving", "sevgi"],
  ["low", "past"],
  ["lowly", "kam"],
  ["lucky", "omadli"],
  ["ludicrous", "jozibali"],
  ["lumpy", "paxta"],
  ["lush", "guruch"],
  ["luxuriant", "ulkan"],
  ["lying", "yolg'on gapirish"],
  ["lyrical", "lirik"],
  ["macabre", "yovuzlik"],
  ["macho", "macho"],
  ["maddening", "jinnilikda"],
  ["madly", "jinnilikda"],
  ["magenta", "qirmizi"],
  ["magical", "sehrli"],
  ["magnificent", "ajoyib"],
  ["majestic", "ajoyib"],
  ["makeshift", "vayron qilish"],
  ["male", "erkak"],
  ["malicious", "zararli"],
  ["mammoth", "mamont"],
  ["maniacal", "maniakal"],
  ["many", "ko'pchilik"],
  ["marked", "belgilangan"],
  ["massive", "katta"],
  ["married", "turmushga chiqqan"],
  ["marvelous", "ajoyib"],
  ["material", "materiallar"],
  ["materialistic", "materialistik"],
  ["mature", "etuk"],
  ["mean", "anglatadi"],
  ["measly", "o'lchamli"],
  ["meaty", "go'shtli"],
  ["medical", "tibbiy"],
  ["meek", "kamtarin"],
  ["mellow", "mellow"],
  ["melodic", "ohangdor"],
  ["melted", "erigan"],
  ["merciful", "rahmdil"],
  ["mere", "Faqatgina"],
  ["messy", "iflos"],
  ["mighty", "qudratli"],
  ["military", "harbiylar"],
  ["milky", "sutli"],
  ["mindless", "aqlsiz"],
  ["miniature", "miniatyura"],
  ["minor", "kichik"],
  ["miscreant", "noto'g'ri"],
  ["misty", "mo''tadil"],
  ["mixed", "aralashgan"],
  ["moaning", "nola qilish"],
  ["modern", "zamonaviy"],
  ["moldy", "mog'orlangan"],
  ["momentous", "muhim ahamiyatga ega"],
  ["motionless", "harakatsiz"],
  ["mountainous", "tog'li"],
  ["muddled", "xiralashgan"],
  ["mundane", "dunyoviy"],
  ["murky", "murakkab"],
  ["mushy", "mushy"],
  ["mute", "ovozsiz"],
  ["mysterious", "sirli"],
  ["naive", "sodda"],
  ["nappy", "nappy"],
  ["narrow", "tor"],
  ["nasty", "yomon"],
  ["natural", "tabiiy"],
  ["naughty", "yaramaydi"],
  ["nauseating", "nafas olish"],
  ["near", "yaqin"],
  ["neat", "pokiza"],
  ["nebulous", "nebulous"],
  ["necessary", "kerak"],
  ["needless", "keraksiz"],
  ["needy", "muhtoj"],
  ["neighborly", "qo'shnichilik bilan"],
  ["nervous", "asabli"],
  ["new", "yangi"],
  ["next", "Keyingi"],
  ["nice", "yaxshi"],
  ["nifty", "uyqusiz"],
  ["nimble", "tezkor"],
  ["nine", "to'qqiz"],
  ["nippy", "nippy"],
  ["noiseless", "tovushsiz"],
  ["noisy", "shovqinli"],
  ["nonchalant", "nochalant"],
  ["nondescript", "nondescript"],
  ["nonstop", "to'xtovsiz"],
  ["normal", "normal"],
  ["nostalgic", "nostaljik"],
  ["nosy", "qiziquvchan"],
  ["noxious", "zararli"],
  ["null", "null"],
  ["numberless", "sonli"],
  ["numerous", "ko'pchilik"],
  ["nutritious", "to'yimli"],
  ["nutty", "ifloslik"],
  ["oafish", "oafish"],
  ["obedient", "itoatkor"],
  ["obeisant", "obiizant"],
  ["obese", "obez"],
  ["obnoxious", "jirkanch"],
  ["obscene", "odobsiz"],
  ["obsequious", "yaltiroq"],
  ["observant", "kuzatuvchi"],
  ["obsolete", "eskirgan"],
  ["obtainable", "olish mumkin"],
  ["oceanic", "okeanik"],
  ["odd", "g'alati"],
  ["offbeat", "noqulay"],
  ["old", "qari"],
  ["old-fashioned", "eski moda"],
  ["omniscient", "omniscient"],
  ["one", "biri"],
  ["onerous", "og'ir"],
  ["open", "ochiq"],
  ["opposite", "qarshi"],
  ["optimal", "maqbul"],
  ["orange", "apelsin"],
  ["ordinary", "oddiy"],
  ["organic", "organik"],
  ["ossified", "ossified"],
  ["outgoing", "chiquvchi"],
  ["outrageous", "shafqatsiz"],
  ["outstanding", "ajoyib"],
  ["oval", "tuxumsimon"],
  ["overconfident", "ishonchsiz"],
  ["overjoyed", "mamnuniyat bilan"],
  ["overrated", "overrated"],
  ["overt", "ochiq"],
  ["overwrought", "qochib ketgan"],
  ["painful", "alamli"],
  ["painstaking", "chidamli"],
  ["pale", "rangsiz"],
  ["paltry", "paltry"],
  ["panicky", "xavotirli"],
  ["panoramic", "panoramik"],
  ["parallel", "parallel"],
  ["parched", "qovurilgan"],
  ["parsimonious", "xushbichim"],
  ["past", "o'tgan"],
  ["pastoral", "pastoral"],
  ["pathetic", "achinarli"],
  ["peaceful", "tinch"],
  ["penitent", "tavba qilganlar"],
  ["perfect", "mukammal"],
  ["periodic", "davriy"],
  ["permissible", "joizdir"],
  ["perpetual", "doimiy"],
  ["petite", "ozgina"],
  ["petite", "ozgina"],
  ["phobic", "fobiya"],
  ["physical", "jismoniy"],
  ["picayune", "picayune"],
  ["pink", "pushti"],
  ["piquant", "teshik"],
  ["placid", "sekin"],
  ["plain", "tekis"],
  ["plant", "o'simlik"],
  ["plastic", "plastik"],
  ["plausible", "mantiqiy"],
  ["pleasant", "yoqimli"],
  ["plucky", "jirkanch"],
  ["pointless", "ma'nosiz"],
  ["poised", "tayyorlanmoqda"],
  ["polite", "muloyim"],
  ["political", "siyosiy"],
  ["poor", "kambag'al"],
  ["possessive", "ixtiyoriy"],
  ["possible", "mumkin"],
  ["powerful", "kuchli"],
  ["precious", "qimmatli"],
  ["premium", "ga oshdi"],
  ["present", "mavjud"],
  ["pretty", "yoqimli"],
  ["previous", "oldingi"],
  ["pricey", "qimmat"],
  ["prickly", "tuxumdon"],
  ["private", "xususiy"],
  ["probable", "mumkin"],
  ["productive", "samarali"],
  ["profuse", "juda ko'p"],
  ["protective", "himoya qilish"],
  ["proud", "mag'rurlik"],
  ["psychedelic", "psychedelic"],
  ["psychotic", "psixotik"],
  ["public", "ommaviy"],
  ["puffy", "puffy"],
  ["pumped", "pompalanadi"],
  ["puny", "joni"],
  ["purple", "siyohrang"],
  ["purring", "purring"],
  ["pushy", "tajovuzkor"],
  ["puzzled", "hayron qoldik"],
  ["puzzling", "hayratlanarli"],
  ["quack", "suzish"],
  ["quaint", "shirin"],
  ["quarrelsome", "janjalli"],
  ["questionable", "shubhali"],
  ["quick", "tezkor"],
  ["quickest", "eng tezkor"],
  ["quiet", "jim"],
  ["quirky", "qiziqarli"],
  ["quixotic", "quixotik"],
  ["quizzical", "quizzolik"],
  ["rabid", "qo'zg'olon"],
  ["racial", "irqiy"],
  ["ragged", "siqilgan"],
  ["rainy", "yomg'irli"],
  ["rambunctious", "rambunktor"],
  ["rampant", "keng tarqalgan"],
  ["rapid", "tez"],
  ["rare", "kam"],
  ["raspy", "raspy"],
  ["ratty", "ratty"],
  ["ready", "tayyor"],
  ["real", "haqiqiy"],
  ["rebel", "isyonchi"],
  ["receptive", "qabul qiluvchi"],
  ["recondite", "qayta ishlangan"],
  ["red", "qizil rangli"],
  ["redundant", "keraksiz"],
  ["reflective", "aks ettiradi"],
  ["regular", "muntazam ravishda"],
  ["relieved", "bo'shab qoldi"],
  ["remarkable", "diqqatga sazovor"],
  ["reminiscent", "eslatib turadi"],
  ["repulsive", "jirkanch"],
  ["resolute", "qat'iy"],
  ["resonant", "rezonans"],
  ["responsible", "javobgar"],
  ["rhetorical", "ritorik"],
  ["rich", "boy"],
  ["right", "o'ng"],
  ["righteous", "solih"],
  ["rightful", "haqli"],
  ["rigid", "qattiq"],
  ["ripe", "pishgan"],
  ["ritzy", "ritzy"],
  ["roasted", "qovurilgan"],
  ["robust", "mustahkam"],
  ["romantic", "ishqiy"],
  ["roomy", "keng"],
  ["rotten", "chirigan"],
  ["rough", "qo'pol"],
  ["round", "yumaloq"],
  ["royal", "qirollik"],
  ["ruddy", "ruddy"],
  ["rude", "qo'pol"],
  ["rural", "qishloq"],
  ["rustic", "rustik"],
  ["ruthless", "shafqatsiz"],
  ["sable", "mumkin"],
  ["sad", "xafa"],
  ["safe", "xavfsiz"],
  ["salty", "sho'rlangan"],
  ["same", "bir xil"],
  ["sassy", "sassy"],
  ["satisfying", "qoniqarli"],
  ["savory", "mazali"],
  ["scandalous", "janjal"],
  ["scarce", "kam"],
  ["scared", "qo'rqib ketdim"],
  ["scary", "qo'rqinchli"],
  ["scattered", "tarqalgan"],
  ["scientific", "ilmiy"],
  ["scintillating", "sintez qilish"],
  ["scrawny", "qirib tashlangan"],
  ["screeching", "shivirlash"],
  ["second", "ikkinchi"],
  ["second-hand", "ishlatilgan"],
  ["secret", "sir"],
  ["secretive", "yashirin"],
  ["sedate", "sedate"],
  ["seemly", "ko'rinadi"],
  ["selective", "tanlangan"],
  ["selfish", "xudbinlik"],
  ["separate", "alohida"],
  ["serious", "jiddiy"],
  ["shaggy", "shaggy"],
  ["shaky", "shang'illadi"],
  ["shallow", "sayoz"],
  ["sharp", "o'tkir"],
  ["shiny", "yorqin"],
  ["shivering", "titray boshladi"],
  ["shocking", "zarba beruvchi"],
  ["short", "qisqa"],
  ["shrill", "shilinadi"],
  ["shut", "yopish"],
  ["shy", "uyatchang"],
  ["sick", "kasal"],
  ["silent", "jim"],
  ["silent", "jim"],
  ["silky", "ipeksi"],
  ["silly", "ahmoqona"],
  ["simple", "oddiy"],
  ["simplistic", "soddalashtirilgan"],
  ["sincere", "samimiy"],
  ["six", "olti"],
  ["skillful", "mohirlik"],
  ["skinny", "jasur"],
  ["sleepy", "uyqusiz"],
  ["slim", "nozik"],
  ["slimy", "soxta"],
  ["slippery", "sirg'anchiq"],
  ["sloppy", "noqulay"],
  ["slow", "sekin"],
  ["small", "kichik"],
  ["smart", "aqlli"],
  ["smelly", "hidlash"],
  ["smiling", "jilmayib"],
  ["smoggy", "tutunli"],
  ["smooth", "silliq"],
  ["sneaky", "yashirincha"],
  ["snobbish", "snobbish"],
  ["snotty", "xiralashgan"],
  ["soft", "yumshoq"],
  ["soggy", "hush kelibsiz"],
  ["solid", "qattiq"],
  ["somber", "bechora"],
  ["sophisticated", "murakkab"],
  ["sordid", "jirkanch"],
  ["sore", "jarohatlangan"],
  ["sore", "jarohatlangan"],
  ["sour", "nordon"],
  ["sparkling", "yorqin"],
  ["special", "maxsus"],
  ["spectacular", "ajoyib"],
  ["spicy", "baharatlı"],
  ["spiffy", "spiffy"],
  ["spiky", "spiky"],
  ["spiritual", "ma'naviy"],
  ["spiteful", "jirkanch"],
  ["splendid", "ajoyib"],
  ["spooky", "qo'rqinchli"],
  ["spotless", "beg'ubor"],
  ["spotted", "ko'rindi"],
  ["spotty", "sersuv"],
  ["spurious", "yolg'onchi"],
  ["squalid", "jirkanch"],
  ["square", "kvadrat"],
  ["squealing", "siqish"],
  ["squeamish", "chayqalish"],
  ["staking", "staking"],
  ["stale", "eskirgan"],
  ["standing", "turgan joy"],
  ["statuesque", "haykalcha"],
  ["steadfast", "sabr qiling"],
  ["steady", "barqaror"],
  ["steep", "tik"],
  ["stereotyped", "stereotiplar"],
  ["sticky", "yopishqoq"],
  ["stiff", "qattiq"],
  ["stimulating", "ogohlantiruvchi"],
  ["stingy", "jirkanch"],
  ["stormy", "bo'ronli"],
  ["straight", "To'g'riga"],
  ["strange", "g'alati"],
  ["striped", "chiziqli"],
  ["strong", "kuchli"],
  ["stupendous", "ulkan"],
  ["stupid", "ahmoq"],
  ["sturdy", "mustahkam"],
  ["subdued", "bo'ysundirdi"],
  ["subsequent", "keyinchalik"],
  ["substantial", "muhim ahamiyatga ega"],
  ["successful", "omadli"],
  ["succinct", "qisqa"],
  ["sudden", "kutilmaganda"],
  ["sulky", "sershovak"],
  ["super", "super"],
  ["superb", "ajoyib"],
  ["superficial", "yuzaki"],
  ["supreme", "oliy"],
  ["swanky", "shang'illab"],
  ["sweet", "shirin"],
  ["sweltering", "shivirlash"],
  ["swift", "tezkor"],
  ["symptomatic", "semptomatik"],
  ["synonymous", "Shu bilan birga"],
  ["taboo", "tabu"],
  ["tacit", "tacit"],
  ["tacky", "yopishqoq"],
  ["talented", "iste'dodli"],
  ["tall", "baland"],
  ["tame", "xushbichim"],
  ["tan", "tan"],
  ["tangible", "sezilarli"],
  ["tangy", "tangy"],
  ["tart", "tort"],
  ["tasteful", "qiziqarli"],
  ["tasteless", "noaniq"],
  ["tasty", "mazali"],
  ["tawdry", "tawdry"],
  ["tearful", "ko'z yoshlari"],
  ["tedious", "zerikarli"],
  ["teeny", "o'lik"],
  ["teeny-tiny", "kichik-kichik"],
  ["telling", "aytmoq"],
  ["temporary", "vaqtinchalik"],
  ["ten", "o'nda"],
  ["tender", "tender"],
  ["tense", "zo'riqish"],
  ["tense", "zo'riqish"],
  ["tenuous", "shafqatsiz"],
  ["terrible", "qo'rqinchli"],
  ["terrific", "dahshatli"],
  ["tested", "sinovdan o'tkazildi"],
  ["testy", "moyillik"],
  ["thankful", "minnatdor"],
  ["therapeutic", "terapevtik"],
  ["thick", "qalin"],
  ["thin", "nozik"],
  ["thinkable", "mulohazali"],
  ["third", "uchinchisi"],
  ["thirsty", "chanqoq"],
  ["thirsty", "chanqoq"],
  ["thoughtful", "ehtiyotkorlik bilan"],
  ["thoughtless", "o'ylamasdan"],
  ["threatening", "tahdid qilmoqda"],
  ["three", "uchta"],
  ["thundering", "momaqaldiroq"],
  ["tidy", "toza"],
  ["tight", "qattiq"],
  ["tightfisted", "chuqurlashdi"],
  ["tiny", "kichik"],
  ["tired", "charchagan"],
  ["tiresome", "zerikarli"],
  ["toothsome", "tishli"],
  ["torpid", "torpid"],
  ["tough", "qiyin"],
  ["towering", "kuchliroq"],
  ["tranquil", "tinch"],
  ["trashy", "axlat"],
  ["tremendous", "ulkan"],
  ["tricky", "qiyin"],
  ["trite", "eng qudratli"],
  ["troubled", "muammoli"],
  ["truculent", "haqoratli"],
  ["true", "haqiqiy"],
  ["truthful", "haqiqat"],
  ["two", "ikkita"],
  ["typical", "odatda"],
  ["ubiquitous", "har joyda"],
  ["ugliest", "eng yomoni"],
  ["ugly", "yomon"],
  ["ultra", "ultra"],
  ["unable", "mumkin emas"],
  ["unaccountable", "hisobga olinmaydi"],
  ["unadvised", "unadvised"],
  ["unarmed", "qurolsiz"],
  ["unbecoming", "foydasiz"],
  ["unbiased", "xolis"],
  ["uncovered", "ochilgan"],
  ["understood", "tushunilgan"],
  ["undesirable", "istalmagan"],
  ["unequal", "teng bo'lmagan"],
  ["unequaled", "tengsiz"],
  ["uneven", "notekis"],
  ["unhealthy", "noto'g'ri"],
  ["uninterested", "qiziqtirmagan"],
  ["unique", "noyob"],
  ["unkempt", "noaniq"],
  ["unknown", "noma'lum"],
  ["unnatural", "tabiiy bo'lmagan"],
  ["unruly", "asossiz"],
  ["unsightly", "noqulay"],
  ["unsuitable", "yaroqsiz"],
  ["untidy", "tartibsiz"],
  ["unused", "foydalanilmagan"],
  ["unusual", "noodatiy"],
  ["unwieldy", "noqulay"],
  ["unwritten", "yozilmagan"],
  ["upbeat", "yaxshi"],
  ["uppity", "balandligi"],
  ["upset", "xafa"],
  ["uptight", "chuqurlik"],
  ["used", "ishlatilgan"],
  ["useful", "foydali"],
  ["useless", "foydasiz"],
  ["utopian", "utopik"],
  ["utter", "utter"],
  ["uttermost", "butunlay"],
  ["vacuous", "bo'sh"],
  ["vagabond", "vagabond"],
  ["vague", "noaniq"],
  ["valuable", "qimmatli"],
  ["various", "turli xil"],
  ["vast", "katta"],
  ["vengeful", "qasos"],
  ["venomous", "zaharli"],
  ["verdant", "haydovchi"],
  ["versed", "bilgan"],
  ["victorious", "g'olib"],
  ["vigorous", "kuchli"],
  ["violent", "zo'ravonlik"],
  ["violet", "binafsha"],
  ["vivacious", "jonli"],
  ["voiceless", "ovozsiz"],
  ["volatile", "uchuvchi"],
  ["voracious", "jirkanch"],
  ["vulgar", "shafqatsiz"],
  ["wacky", "mantiqiy"],
  ["waggish", "to'lqinli"],
  ["waiting", "kutish"],
  ["wakeful", "uyg'oq"],
  ["wandering", "yugurish"],
  ["wanting", "istagan"],
  ["warlike", "urushga o'xshash"],
  ["warm", "issiq"],
  ["wary", "ehtiyot bo'ling"],
  ["wasteful", "isrofgarchilik"],
  ["watery", "suvli"],
  ["weak", "zaif"],
  ["wealthy", "boy"],
  ["weary", "charchagan"],
  ["well-groomed", "yaxshi jihozlangan"],
  ["well-made", "yaxshi tayyorlangan"],
  ["well-off", "taniqli"],
  ["well-to-do", "yaxshi bajarilish"],
  ["wet", "nam"],
  ["whimsical", "jozibali"],
  ["whispering", "pichirladi"],
  ["white", "oq"],
  ["whole", "butun"],
  ["wholesale", "butunlay sotish"],
  ["wicked", "yomon"],
  ["wide", "keng"],
  ["wide-eyed", "keng ko'zli"],
  ["wiggly", "chaqqonlik"],
  ["wild", "yovvoyi"],
  ["willing", "tayyor"],
  ["windy", "shamolli"],
  ["wiry", "wiry"],
  ["wise", "dono"],
  ["wistful", "jirkanch"],
  ["witty", "jozibali"],
  ["woebegone", "woegegone"],
  ["womanly", "ayollar"],
  ["wonderful", "ajoyib"],
  ["wooden", "yog'och"],
  ["woozy", "woozy"],
  ["workable", "ishlaydigan"],
  ["worried", "tashvishlangan"],
  ["worthless", "foydasiz"],
  ["wrathful", "G'azablangan"],
  ["wretched", "baxtsiz"],
  ["wrong", "noto'g'ri"],
  ["wry", "xolos"],
  ["yellow", "sariq rangda"],
  ["yielding", "hosil bo'lgan"],
  ["young", "yosh"],
  ["youthful", "yoshlar"],
  ["yummy", "mazali"],
  ["zany", "zany"],
  ["zealous", "g'ayratli"],
  ["zesty", "zaytun"],
  ["zippy", "zippy"],
  ["zonked", "zonked"],
  ["account", "hisob qaydnomasi"],
  ["achiever", "achigan kishi"],
  ["acoustics", "akustika"],
  ["act", "harakat qilish"],
  ["action", "harakatlar"],
  ["activity", "faoliyati"],
  ["actor", "aktyor"],
  ["addition", "qo'shimcha"],
  ["adjustment", "moslashish"],
  ["advertisement", "reklama"],
  ["advice", "maslahat"],
  ["aftermath", "keyin"],
  ["afternoon", "tushdan keyin"],
  ["afterthought", "keyinchalik"],
  ["agreement", "kelishuv"],
  ["air", "havo"],
  ["airplane", "samolyot"],
  ["airport", "aeroport"],
  ["alarm", "ogohlantirish"],
  ["amount", "miqdori"],
  ["amusement", "o'yin-kulgi"],
  ["anger", "g'azab"],
  ["angle", "burchak"],
  ["animal", "hayvon"],
  ["ants", "chumolilar"],
  ["apparatus", "apparati"],
  ["apparel", "kiyim-kechak"],
  ["appliance", "asbobdan foydalaning"],
  ["approval", "tasdiqlash"],
  ["arch", "kamar"],
  ["argument", "dalil"],
  ["arithmetic", "arifmetik"],
  ["arm", "qo'l"],
  ["army", "armiya"],
  ["art", "san'at"],
  ["attack", "hujum"],
  ["attraction", "diqqatga sazovor joy"],
  ["aunt", "xolasi"],
  ["authority", "hokimiyat"],
  ["babies", "Chaqaloqlar"],
  ["baby", "chaqaloq"],
  ["back", "orqaga"],
  ["badge", "rozet"],
  ["bag", "yukxalta"],
  ["bait", "o'lja"],
  ["balance", "muvozanat"],
  ["ball", "to'p"],
  ["base", "bazasi"],
  ["baseball", "beysbol"],
  ["basin", "havzasi"],
  ["basket", "savat"],
  ["basketball", "basketbol"],
  ["bat", "bat"],
  ["bath", "Vanna"],
  ["battle", "jang"],
  ["bead", "boncuk"],
  ["bear", "ayiq"],
  ["bed", "yotoqda"],
  ["bedroom", "yotoq xonasi"],
  ["beds", "yotoqlari"],
  ["bee", "asalarilar"],
  ["beef", "mol go'shti"],
  ["beginner", "boshlang'ich"],
  ["behavior", "harakatlar"],
  ["belief", "e'tiqod"],
  ["believe", "ishonish"],
  ["bell", "qo'ng'iroq"],
  ["bells", "qo'ng'iroqlar"],
  ["berry", "berry"],
  ["bike", "velosiped"],
  ["bikes", "velosipedlar"],
  ["bird", "qush"],
  ["birds", "qushlar"],
  ["birth", "tug'ilish"],
  ["birthday", "tug'ilgan kun"],
  ["bit", "bit"],
  ["bite", "luqma"],
  ["blade", "blade"],
  ["blood", "qon"],
  ["blow", "puflamoq"],
  ["board", "taxta"],
  ["boat", "qayiq"],
  ["bomb", "bomba"],
  ["bone", "suyak"],
  ["book", "kitob"],
  ["books", "kitoblar"],
  ["boot", "yuklash"],
  ["border", "chegara"],
  ["bottle", "shisha"],
  ["boundary", "chegarasi"],
  ["box", "qutisi"],
  ["boy", "bola"],
  ["brake", "tormozlanadi"],
  ["branch", "filiali"],
  ["brass", "guruch"],
  ["breath", "nafas olish"],
  ["brick", "g'isht"],
  ["bridge", "ko'prik"],
  ["brother", "birodar"],
  ["bubble", "qabariq"],
  ["bucket", "kepçe"],
  ["building", "bino"],
  ["bulb", "Lampochka"],
  ["burst", "portlash"],
  ["bushes", "butalar"],
  ["business", "biznes"],
  ["butter", "sariyog'"],
  ["button", "tugmasini bosing"],
  ["cabbage", "karam"],
  ["cable", "kabel"],
  ["cactus", "kaktus"],
  ["cake", "kek"],
  ["cakes", "kek"],
  ["calculator", "kalkulyator"],
  ["calendar", "taqvim"],
  ["camera", "kamera"],
  ["camp", "lager"],
  ["can", "mumkin"],
  ["cannon", "to'p"],
  ["canvas", "kanvas"],
  ["cap", "qopqoq"],
  ["caption", "sarlavhasi"],
  ["car", "mashina"],
  ["card", "karta"],
  ["care", "parvarishlash"],
  ["carpenter", "duradgor"],
  ["carriage", "tashish"],
  ["cars", "mashinalar"],
  ["cart", "arava"],
  ["cast", "quyma"],
  ["cat", "mushuk"],
  ["cattle", "chorva mollari"],
  ["cause", "sababi"],
  ["cave", "g'or"],
  ["celery", "seldr"],
  ["cellar", "qabrlar"],
  ["cemetery", "qabriston"],
  ["cent", "sent"],
  ["chalk", "tebeşir"],
  ["chance", "imkoniyat"],
  ["change", "o'zgartirish"],
  ["channel", "kanal"],
  ["cheese", "pishloq"],
  ["cherries", "Gilos"],
  ["cherry", "gilos"],
  ["chess", "shaxmat"],
  ["chicken", "tovuq"],
  ["chickens", "tovuqlar"],
  ["children", "bolalar"],
  ["chin", "chinni"],
  ["church", "cherkov"],
  ["circle", "doira"],
  ["clam", "jala"],
  ["class", "sinf"],
  ["cloth", "mato bilan qoplangan"],
  ["clover", "yonca"],
  ["club", "klub"],
  ["coach", "murabbiy"],
  ["coal", "ko'mir"],
  ["coast", "qirg'oq"],
  ["coat", "qoplama"],
  ["cobweb", "qobiq"],
  ["coil", "lasan"],
  ["collar", "yoqa"],
  ["color", "rangi"],
  ["committee", "qo'mitasi"],
  ["company", "kompaniya"],
  ["comparison", "taqqoslash"],
  ["competition", "musobaqa"],
  ["condition", "holati"],
  ["connection", "ulanish"],
  ["control", "boshqaruv"],
  ["cook", "oshpaz"],
  ["copper", "mis"],
  ["corn", "makkajo'xori"],
  ["cough", "yo'tal"],
  ["country", "mamlakat"],
  ["cover", "qopqoq"],
  ["cow", "sigir"],
  ["cows", "sigirlar"],
  ["crack", "yoriq"],
  ["cracker", "kraker"],
  ["crate", "kassa"],
  ["crayon", "bo'yoq"],
  ["cream", "krem"],
  ["creator", "yaratuvchisi"],
  ["creature", "jonzot"],
  ["credit", "kredit"],
  ["crib", "yostig'i"],
  ["crime", "jinoyat"],
  ["crook", "zarba"],
  ["crow", "qarg'a"],
  ["crowd", "olomon"],
  ["crown", "toj"],
  ["cub", "kubik"],
  ["cup", "chashka"],
  ["current", "joriy"],
  ["curtain", "parda"],
  ["curve", "egri"],
  ["cushion", "yostiq"],
  ["dad", "Dad"],
  ["daughter", "qizim"],
  ["day", "kun"],
  ["death", "o'lim"],
  ["debt", "qarz"],
  ["decision", "qaror"],
  ["deer", "kiyik"],
  ["degree", "daraja"],
  ["design", "dizayn"],
  ["desire", "orzu"],
  ["desk", "stol"],
  ["destruction", "yo'q qilish"],
  ["detail", "batafsil ma'lumot"],
  ["development", "rivojlanish"],
  ["digestion", "hazm qilish"],
  ["dime", "dima"],
  ["dinner", "kechki ovqat"],
  ["dinosaurs", "dinozavrlar"],
  ["direction", "yo'nalish"],
  ["dirt", "axloqsizlik"],
  ["discovery", "kashfiyot"],
  ["discussion", "munozarasi"],
  ["distance", "masofa"],
  ["distribution", "tarqatish"],
  ["division", "bo'linish"],
  ["dock", "dock"],
  ["doctor", "shifokor"],
  ["dog", "it"],
  ["dogs", "itlar"],
  ["doll", "chaqaloq"],
  ["dolls", "chaqaloqlar"],
  ["donkey", "eshak"],
  ["door", "eshik"],
  ["downtown", "shahar markazida"],
  ["drain", "drenajlash"],
  ["drawer", "tortmasin"],
  ["dress", "kiyim"],
  ["drink", "ichimlik"],
  ["driving", "haydash"],
  ["drop", "tomchi"],
  ["duck", "o'rdak"],
  ["ducks", "o'rdak"],
  ["dust", "chang"],
  ["ear", "quloq"],
  ["earth", "tuproq"],
  ["earthquake", "zilzila"],
  ["edge", "qirrasi"],
  ["education", "ta'lim"],
  ["effect", "ta'siri"],
  ["egg", "tuxum"],
  ["eggnog", "eggnog"],
  ["eggs", "tuxum"],
  ["elbow", "tirsak"],
  ["end", "oxiri"],
  ["engine", "vosita"],
  ["error", "xatolik"],
  ["event", "voqea"],
  ["example", "misol"],
  ["exchange", "almashtirish"],
  ["existence", "mavjudlik"],
  ["expansion", "kengaytirish"],
  ["experience", "tajriba"],
  ["expert", "mutaxassis"],
  ["eye", "ko'z"],
  ["eyes", "ko'zlar"],
  ["face", "yuzi"],
  ["fact", "haqiqat"],
  ["fairies", "peri"],
  ["fall", "tushishi"],
  ["fang", "fang"],
  ["farm", "fermerlik xo'jaligi"],
  ["fear", "qo'rquv"],
  ["feeling", "his qilish"],
  ["field", "maydon"],
  ["finger", "barmoq"],
  ["finger", "barmoq"],
  ["fire", "olov"],
  ["fireman", "o't o'chiruvchilar"],
  ["fish", "baliq"],
  ["flag", "bayroq"],
  ["flame", "olov"],
  ["flavor", "lazzat"],
  ["flesh", "go'sht"],
  ["flight", "parvoz"],
  ["flock", "suruv"],
  ["floor", "qavat"],
  ["flower", "gullar"],
  ["flowers", "gullar"],
  ["fly", "pashsha"],
  ["fog", "tuman"],
  ["fold", "qatlam"],
  ["food", "ovqat"],
  ["foot", "oyog'i"],
  ["force", "kuch"],
  ["fork", "vilkalar"],
  ["form", "shakl"],
  ["fowl", "parranda"],
  ["frame", "ramka"],
  ["friction", "ishqalanish"],
  ["friend", "do'stim"],
  ["friends", "do'stlarim"],
  ["frog", "qurbaqa"],
  ["frogs", "qurbaqalar"],
  ["front", "oldida"],
  ["fruit", "mevalar"],
  ["fuel", "yonilg'i"],
  ["furniture", "mebel"],
  ["gate", "Darvoza"],
  ["geese", "g'ozlar"],
  ["ghost", "ruh"],
  ["giants", "gigantlar"],
  ["giraffe", "Jirafa"],
  ["girl", "qiz"],
  ["girls", "qizlar"],
  ["glass", "shisha"],
  ["glove", "qo'lqop"],
  ["gold", "oltin"],
  ["government", "hukumat"],
  ["governor", "hokim"],
  ["grade", "daraja"],
  ["grain", "don"],
  ["grandfather", "bobosi"],
  ["grandmother", "buvim"],
  ["grape", "uzum"],
  ["grass", "o'tlar"],
  ["grip", "tushunish"],
  ["ground", "joy"],
  ["group", "guruh"],
  ["growth", "o'sishi"],
  ["guide", "ko'rsatma"],
  ["guitar", "gitara"],
  ["gun", "qurol"],
  ["hair", "Soch"],
  ["haircut", "soch kesish"],
  ["hall", "zal"],
  ["hammer", "bolg'a"],
  ["hand", "qo'l"],
  ["hands", "qo'llar"],
  ["harbor", "port"],
  ["harmony", "Garmoniya"],
  ["hat", "shapka"],
  ["hate", "nafratlanish"],
  ["head", "boshi"],
  ["health", "sog'liqni saqlash"],
  ["heat", "issiqlik"],
  ["hill", "tepalik"],
  ["history", "tarix"],
  ["hobbies", "sevimli mashg'ulotlariga"],
  ["hole", "teshik"],
  ["holiday", "dam olish"],
  ["home", "uy"],
  ["honey", "asal"],
  ["hook", "kanca"],
  ["hope", "umid qilamiz"],
  ["horn", "shoxi"],
  ["horse", "ot"],
  ["horses", "otlar"],
  ["hose", "shlang"],
  ["hospital", "shifoxona"],
  ["hot", "issiq"],
  ["hour", "soat"],
  ["house", "uy"],
  ["houses", "uylar"],
  ["humor", "hazil"],
  ["hydrant", "hidrant"],
  ["ice", "muz"],
  ["icicle", "buzuqlik"],
  ["idea", "fikr"],
  ["impulse", "impuls"],
  ["income", "daromad"],
  ["increase", "o'sish"],
  ["industry", "sanoat"],
  ["ink", "siyoh"],
  ["insect", "hasharotlar"],
  ["instrument", "asbob"],
  ["insurance", "sug'urta"],
  ["interest", "qiziqish"],
  ["invention", "kashfiyot"],
  ["iron", "temir moddasi"],
  ["island", "orol"],
  ["jail", "qamoqxona"],
  ["jam", "murabbo"],
  ["jar", "jar"],
  ["jeans", "jinsi"],
  ["jelly", "jele"],
  ["jellyfish", "meduza"],
  ["jewel", "marvarid"],
  ["join", "qo'shiling"],
  ["judge", "hukm qilish"],
  ["juice", "sharbat"],
  ["jump", "sakramoq"],
  ["kettle", "choynak"],
  ["key", "kalit"],
  ["kick", "kick"],
  ["kiss", "o'pish"],
  ["kittens", "mushukchalar"],
  ["kitty", "peshtoq"],
  ["knee", "tizza"],
  ["knife", "pichoq"],
  ["knot", "tugun"],
  ["knowledge", "bilim"],
  ["laborer", "ishchi"],
  ["lace", "dantel"],
  ["ladybug", "ladybug"],
  ["lake", "ko'l"],
  ["lamp", "chiroq"],
  ["land", "er"],
  ["language", "tili"],
  ["laugh", "kulmoq"],
  ["leather", "teri"],
  ["leg", "oyoq"],
  ["legs", "oyoqlari"],
  ["letter", "xat"],
  ["letters", "harflari"],
  ["lettuce", "sutcho'p"],
  ["level", "Daraja"],
  ["library", "kutubxona"],
  ["limit", "chegarasi"],
  ["line", "yo'nalish"],
  ["linen", "zig'ir"],
  ["lip", "lab"],
  ["liquid", "suyuqlik"],
  ["loaf", "non"],
  ["lock", "qulflash"],
  ["locket", "plitkasi"],
  ["look", "qara"],
  ["loss", "zarar"],
  ["love", "sevgi"],
  ["low", "past"],
  ["lumber", "yog'och"],
  ["lunch", "tushlik"],
  ["lunchroom", "ovqat xonasi"],
  ["machine", "mashina"],
  ["magic", "sehrli"],
  ["maid", "xizmatchi"],
  ["mailbox", "pochta qutisi"],
  ["man", "kishi"],
  ["marble", "marmar"],
  ["mark", "belgisi"],
  ["market", "bozor"],
  ["mask", "maska"],
  ["mass", "massa"],
  ["match", "o'yin"],
  ["meal", "ovqat"],
  ["measure", "o'lchov"],
  ["meat", "go'sht"],
  ["meeting", "yig'ilish"],
  ["memory", "xotira"],
  ["men", "erkak"],
  ["metal", "metalldan"],
  ["mice", "sichqonlar"],
  ["middle", "o'rta"],
  ["milk", "sut"],
  ["mind", "aql"],
  ["mine", "meniki"],
  ["minister", "vazir"],
  ["mint", "yalpiz"],
  ["minute", "daqiqada"],
  ["mist", "tuman"],
  ["mitten", "mitten"],
  ["mom", "onam"],
  ["money", "pul"],
  ["monkey", "maymunga"],
  ["month", "oyda"],
  ["moon", "oy"],
  ["morning", "ertalab"],
  ["mother", "Ona"],
  ["motion", "harakati"],
  ["mountain", "tog"],
  ["mouth", "og'iz"],
  ["move", "harakatlaning"],
  ["muscle", "muskul"],
  ["name", "nomi"],
  ["nation", "millat"],
  ["neck", "bo'yin"],
  ["need", "kerak"],
  ["needle", "igna"],
  ["nerve", "asab"],
  ["nest", "uy"],
  ["night", "kecha"],
  ["noise", "shovqin"],
  ["north", "shimolga"],
  ["nose", "burun"],
  ["note", "Eslatma"],
  ["notebook", "notebook"],
  ["number", "raqami"],
  ["nut", "yong'oq"],
  ["oatmeal", "jo'xori"],
  ["observation", "kuzatuv"],
  ["ocean", "okean"],
  ["offer", "taklif"],
  ["office", "idora"],
  ["oil", "yog '"],
  ["orange", "apelsin"],
  ["oranges", "portsiyalar"],
  ["order", "buyurtma"],
  ["oven", "o'choq"],
  ["page", "sahifa"],
  ["pail", "dumaloq"],
  ["pan", "pan"],
  ["pancake", "pista"],
  ["paper", "qog'oz"],
  ["parcel", "Uydagi hamma qavatlar"],
  ["part", "qism"],
  ["partner", "hamkor"],
  ["party", "partiyasi"],
  ["passenger", "yo'lovchi"],
  ["payment", "to'lov"],
  ["peace", "tinchlik"],
  ["pear", "nok"],
  ["pen", "qalam"],
  ["pencil", "qalam"],
  ["person", "shaxs"],
  ["pest", "zararkunanda"],
  ["pet", "Uy hayvoni"],
  ["pets", "uy hayvonlari"],
  ["pickle", "tuzlangan"],
  ["picture", "rasm"],
  ["pie", "pirog"],
  ["pies", "pies"],
  ["pig", "cho'chqa"],
  ["pigs", "cho'chqalar"],
  ["pin", "PIN"],
  ["pipe", "quvur"],
  ["pizzas", "pizzalar"],
  ["place", "joy"],
  ["plane", "samolyot"],
  ["planes", "samolyotlar"],
  ["plant", "o'simlik"],
  ["plantation", "ekish"],
  ["plants", "o'simliklar"],
  ["plastic", "plastik"],
  ["plate", "plitalar"],
  ["play", "o'ynash"],
  ["playground", "o'yin maydoni"],
  ["pleasure", "quvonch"],
  ["plot", "qurulish"],
  ["plough", "pulluk"],
  ["pocket", "cho'ntak"],
  ["point", "nuqta"],
  ["poison", "zahar"],
  ["pollution", "ifloslanish"],
  ["popcorn", "Popkorn"],
  ["porter", "porter"],
  ["position", "holati"],
  ["pot", "qozon"],
  ["potato", "kartoshka"],
  ["powder", "chang"],
  ["power", "kuch"],
  ["price", "narxlari"],
  ["produce", "mahsulot"],
  ["profit", "foyda"],
  ["property", "mulk"],
  ["prose", "nasr"],
  ["protest", "norozilik"],
  ["pull", "Torting"],
  ["pump", "nasosi"],
  ["punishment", "jazo"],
  ["purpose", "maqsadi"],
  ["push", "Durang"],
  ["quarter", "chorak"],
  ["quartz", "kvarts"],
  ["queen", "malika"],
  ["question", "savol"],
  ["quicksand", "quchoq"],
  ["quiet", "jim"],
  ["quill", "shoyi"],
  ["quilt", "yoritgich"],
  ["quince", "behi"],
  ["quiver", "sallanma"],
  ["rabbit", "quyon"],
  ["rabbits", "quyonlar"],
  ["rail", "temir yo'l"],
  ["railway", "temir yo'l"],
  ["rain", "yomg'ir"],
  ["rainstorm", "yomg'ir bo'roni"],
  ["rake", "rake"],
  ["range", "oralig'i"],
  ["rat", "kalamush"],
  ["rate", "darajasi"],
  ["ray", "ray"],
  ["reaction", "reaktsiya"],
  ["reading", "o'qish"],
  ["reason", "sabab"],
  ["receipt", "oling"],
  ["recess", "chuqurlik"],
  ["record", "yozuvlar"],
  ["regret", "pushaymon"],
  ["relation", "munosabatlar"],
  ["religion", "din"],
  ["representative", "vakili"],
  ["request", "so'rov"],
  ["respect", "hurmat qilish"],
  ["rest", "dam olish"],
  ["reward", "sovrin"],
  ["rhythm", "ritm"],
  ["rice", "guruch"],
  ["riddle", "jumboq"],
  ["rifle", "miltiq"],
  ["ring", "qo'ng'iroq qiling"],
  ["rings", "uzuklar"],
  ["river", "daryo"],
  ["road", "yo'l"],
  ["robin", "robin"],
  ["rock", "jinslar"],
  ["rod", "novda"],
  ["roll", "rulo"],
  ["roof", "uyingizda"],
  ["room", "xona"],
  ["root", "ildiz"],
  ["rose", "gul"],
  ["route", "yo'nalish"],
  ["rub", "rub"],
  ["rule", "qoidalar"],
  ["run", "ishga tushirish"],
  ["sack", "xaltadan"],
  ["sail", "suzib"],
  ["salt", "tuz"],
  ["sand", "qum"],
  ["scale", "miqyosi"],
  ["scarecrow", "qo'rqitish"],
  ["scarf", "sharf"],
  ["scene", "sahna"],
  ["scent", "hidi"],
  ["school", "maktab"],
  ["science", "ilm-fan"],
  ["scissors", "qaychi"],
  ["screw", "vint"],
  ["sea", "dengiz"],
  ["seashore", "dengiz sohilida joylashgan"],
  ["seat", "o'rindiq"],
  ["secretary", "kotibi"],
  ["seed", "urug'lar"],
  ["selection", "tanlash"],
  ["self", "o'z-o'zini"],
  ["sense", "ma'no"],
  ["servant", "xizmatkor"],
  ["shade", "soya"],
  ["shake", "silkitardi"],
  ["shame", "sharmandalik"],
  ["shape", "shakli"],
  ["sheep", "qo'ylar"],
  ["sheet", "varaq"],
  ["shelf", "Raf"],
  ["ship", "kema"],
  ["shirt", "ko'ylak"],
  ["shock", "zarba"],
  ["shoe", "poyafzal"],
  ["shoes", "poyabzal"],
  ["shop", "do'kon"],
  ["show", "ko'rsatish"],
  ["side", "tomoni"],
  ["sidewalk", "yulka"],
  ["sign", "belgisi"],
  ["silk", "ipak"],
  ["silver", "kumush"],
  ["sink", "cho'milish"],
  ["sister", "singlim"],
  ["sisters", "opa-singillar"],
  ["size", "hajmi"],
  ["skate", "skat"],
  ["skin", "teri"],
  ["skirt", "etek"],
  ["sky", "osmon"],
  ["slave", "qul"],
  ["sleep", "uyqu"],
  ["sleet", "yomg'ir yog'ishi mumkin"],
  ["slip", "slip"],
  ["slope", "Nishab"],
  ["smash", "sindirish"],
  ["smell", "hid"],
  ["smile", "tabassum"],
  ["smoke", "tutun"],
  ["snail", "salyangoz"],
  ["snails", "shilliq qurtlar"],
  ["snake", "ilon"],
  ["snakes", "ilonlar"],
  ["sneeze", "aksirish"],
  ["snow", "qor"],
  ["soap", "sovun"],
  ["society", "jamiyat"],
  ["sock", "paypoq"],
  ["soda", "soda"],
  ["sofa", "divan"],
  ["son", "o'g'li"],
  ["song", "Qo'shiq"],
  ["songs", "qo'shiqlari"],
  ["sort", "tartibida"],
  ["sound", "ovozi"],
  ["soup", "sho'rva"],
  ["space", "joy"],
  ["spade", "chavandoz"],
  ["spark", "uchqun"],
  ["spiders", "o'rgimchaklar"],
  ["sponge", "shimgichni"],
  ["spoon", "qoshiq"],
  ["spot", "spot"],
  ["spring", "bahor"],
  ["spy", "josuslik"],
  ["square", "kvadrat"],
  ["squirrel", "sincap"],
  ["stage", "bosqichda"],
  ["stamp", "muhri"],
  ["star", "Yulduz"],
  ["start", "boshlang"],
  ["statement", "bayonot"],
  ["station", "stantsiya"],
  ["steam", "Bug '"],
  ["steel", "po'latdir"],
  ["stem", "ildiz"],
  ["step", "qadam"],
  ["stew", "go'sht"],
  ["stick", "tayoq"],
  ["sticks", "tayoqchalar"],
  ["stitch", "stitch"],
  ["stocking", "stoklamoqda"],
  ["stomach", "oshqozon"],
  ["stone", "tosh"],
  ["stop", "To'xta"],
  ["store", "saqlash"],
  ["story", "hikoya"],
  ["stove", "pechka"],
  ["stranger", "begona"],
  ["straw", "somon"],
  ["stream", "oqim"],
  ["street", "ko'cha"],
  ["stretch", "cho'zish"],
  ["string", "string"],
  ["structure", "tuzilishi"],
  ["substance", "modda"],
  ["sugar", "shakar"],
  ["suggestion", "taklif"],
  ["suit", "kostyum"],
  ["summer", "yoz"],
  ["sun", "quyosh"],
  ["support", "qo'llab-quvvatlash"],
  ["surprise", "ajablanib"],
  ["sweater", "kozok"],
  ["swim", "suzish"],
  ["swing", "tebranish"],
  ["system", "tizimi"],
  ["table", "jadval"],
  ["tail", "quyruq"],
  ["talk", "gapirish"],
  ["tank", "tank"],
  ["taste", "ta'mi"],
  ["tax", "soliq"],
  ["teaching", "ta'lim berish"],
  ["team", "jamoa"],
  ["teeth", "tishlar"],
  ["temper", "jo'shqinlik"],
  ["tendency", "tendentsiya"],
  ["tent", "chodir"],
  ["territory", "hududi"],
  ["test", "sinov"],
  ["texture", "to'qimalar"],
  ["theory", "nazariya"],
  ["thing", "narsa"],
  ["things", "narsalar"],
  ["thought", "o'ylardi"],
  ["thread", "ip"],
  ["thrill", "qiziqish uyg'otdi"],
  ["throat", "og'iz"],
  ["throne", "taxt"],
  ["thumb", "thumb"],
  ["thunder", "momaqaldiroq"],
  ["ticket", "chipta"],
  ["tiger", "yo'lbars"],
  ["time", "vaqt"],
  ["tin", "qalay"],
  ["title", "nomi"],
  ["toad", "qurbaqa"],
  ["toe", "oyoq barmog'i"],
  ["toes", "oyoq barmoqlari"],
  ["tomatoes", "pomidor"],
  ["tongue", "til"],
  ["tooth", "tish"],
  ["toothbrush", "tish cho'tkasi"],
  ["toothpaste", "tish pastasi"],
  ["top", "yuqori"],
  ["touch", "tegish"],
  ["town", "shahar"],
  ["toy", "o'yinchoq"],
  ["toys", "o'yinchoqlar"],
  ["trade", "savdo"],
  ["trail", "izlanish"],
  ["train", "poezd"],
  ["trains", "poezdlar"],
  ["tramp", "tramp"],
  ["transport", "transport"],
  ["tray", "laganda"],
  ["treatment", "davolash"],
  ["tree", "daraxt"],
  ["trees", "daraxtlar"],
  ["trick", "aldash"],
  ["trip", "sayohat"],
  ["trouble", "muammo"],
  ["trousers", "shim"],
  ["truck", "yuk mashinalari"],
  ["trucks", "yuk mashinalari"],
  ["tub", "tub"],
  ["turkey", "kurka"],
  ["turn", "qaytish"],
  ["twig", "chig'anoq"],
  ["twist", "twist"],
  ["umbrella", "soyabon"],
  ["uncle", "amaki"],
  ["underwear", "ichki kiyim"],
  ["unit", "birlik"],
  ["use", "foydalanish"],
  ["vacation", "dam olish"],
  ["value", "qiymati"],
  ["van", "van"],
  ["vase", "vaza"],
  ["vegetable", "sabzavot"],
  ["veil", "parda"],
  ["vein", "tomirlar"],
  ["verse", "oyat"],
  ["vessel", "kema"],
  ["vest", "yelek"],
  ["view", "ko'rinish"],
  ["visitor", "Mehmon"],
  ["voice", "ovozi"],
  ["volcano", "vulkan"],
  ["volleyball", "voleybol"],
  ["voyage", "sayohat"],
  ["walk", "yurish"],
  ["wall", "devor"],
  ["war", "urush"],
  ["wash", "yuvish"],
  ["waste", "chiqindi"],
  ["watch", "tomosha qiling"],
  ["water", "suv"],
  ["wave", "to'lqin"],
  ["waves", "to'lqinlar"],
  ["wax", "mum"],
  ["way", "yo'l"],
  ["wealth", "boylik"],
  ["weather", "ob-havo"],
  ["week", "hafta"],
  ["weight", "og'irligi"],
  ["wheel", "g'ildirak"],
  ["whip", "qamchi"],
  ["whistle", "hushtak"],
  ["wilderness", "sahroda"],
  ["wind", "shamol"],
  ["window", "oyna"],
  ["wine", "vino"],
  ["wing", "qanot"],
  ["winter", "qish"],
  ["wire", "tel"],
  ["wish", "istak"],
  ["woman", "ayol"],
  ["women", "ayollar"],
  ["wood", "yog'och"],
  ["wool", "jun"],
  ["word", "so'z"],
  ["work", "ish"],
  ["worm", "solucan"],
  ["wound", "yara"],
  ["wren", "qochish"],
  ["wrench", "kaliti"],
  ["wrist", "bilagini olib tashlang"],
  ["writer", "yozuvchi"],
  ["writing", "yozish"],
  ["yak", "yak"],
  ["yam", "Shirin kartoshka"],
  ["yard", "hovlida"],
  ["yarn", "ip"],
  ["year", "yil"],
  ["yoke", "bo'yinturuq"],
  ["zebra", "zopakda"],
  ["zephyr", "zefir"],
  ["zinc", "sink"],
  ["zipper", "fermuar"],
  ["zoo", "hayvonot bog'i"],
  ["accept", "qabul qiling"],
  ["add", "qo'shing"],
  ["admire", "hayron"],
  ["admit", "tan olish"],
  ["advise", "maslahat bering"],
  ["afford", "ko'z o'ngingizda"],
  ["agree", "qabul qilaman"],
  ["alert", "ogohlantirish"],
  ["allow", "ruxsat berish"],
  ["amuse", "o'yin-kulgi"],
  ["analyse", "tahlil qilish"],
  ["announce", "e'lon qiling"],
  ["annoy", "jahl bilan"],
  ["answer", "javob berish"],
  ["apologise", "uzr so'raymiz"],
  ["appear", "paydo bo'ladi"],
  ["applaud", "olqishlash"],
  ["appreciate", "qadrlayman"],
  ["approve", "tasdiqlang"],
  ["argue", "munozarali"],
  ["arrange", "tartibga solish"],
  ["arrest", "hibsga olish"],
  ["arrive", "keling"],
  ["ask", "so'rang"],
  ["attach", "biriktir"],
  ["attack", "hujum"],
  ["attempt", "tashabbus"],
  ["attend", "qatnashmoq"],
  ["attract", "jalb qilish"],
  ["avoid", "qochish"],
  ["back", "orqaga"],
  ["bake", "pishirib"],
  ["balance", "muvozanat"],
  ["ban", "taqiq"],
  ["bang", "portlash"],
  ["bare", "yalang'och"],
  ["bat", "bat"],
  ["bathe", "batamom"],
  ["battle", "jang"],
  ["beam", "nurlanish"],
  ["beg", "begona"],
  ["behave", "O'zingizni tuting"],
  ["belong", "tegishli"],
  ["bleach", "ağartıcı"],
  ["bless", "muborak bo'l"],
  ["blind", "ko'r"],
  ["blink", "blink"],
  ["blot", "blot"],
  ["blush", "qizarib yuborish"],
  ["boast", "maqtanchoqlik"],
  ["boil", "qaynatiladi"],
  ["bolt", "murvat"],
  ["bomb", "bomba"],
  ["book", "kitob"],
  ["bore", "teshik"],
  ["borrow", "qarz olish"],
  ["bounce", "siqilish"],
  ["bow", "kamon"],
  ["box", "qutisi"],
  ["brake", "tormozlanadi"],
  ["branch", "filiali"],
  ["breathe", "nafas olish"],
  ["bruise", "mushaklar"],
  ["brush", "cho'tka"],
  ["bubble", "qabariq"],
  ["bump", "zarba"],
  ["burn", "kuyish"],
  ["bury", "dafn qilmoq"],
  ["buzz", "buzz"],
  ["calculate", "hisoblash"],
  ["call", "qo'ng'iroq qiling"],
  ["camp", "lager"],
  ["care", "parvarishlash"],
  ["carry", "ko'chirish"],
  ["carve", "o'yib ko'ring"],
  ["cause", "sababi"],
  ["challenge", "muammo"],
  ["change", "o'zgartirish"],
  ["charge", "zaryad qiling"],
  ["chase", "ketidan quvmoq"],
  ["cheat", "makr qilish"],
  ["check", "tekshiring"],
  ["cheer", "hayqiriq"],
  ["chew", "chaynash"],
  ["choke", "taqiqlash"],
  ["chop", "chop etish"],
  ["claim", "Talab"],
  ["clap", "chiroyli"],
  ["clean", "toza"],
  ["clear", "aniq"],
  ["clip", "klip"],
  ["close", "yoping"],
  ["coach", "murabbiy"],
  ["coil", "lasan"],
  ["collect", "to'plash"],
  ["colour", "rangi"],
  ["comb", "taroqsimon"],
  ["command", "buyruq"],
  ["communicate", "muloqot qilish"],
  ["compare", "solishtiring"],
  ["compete", "raqobat qilish"],
  ["complain", "shikoyat qiling"],
  ["complete", "to'liq"],
  ["concentrate", "konsantre qiling"],
  ["concern", "tashvish"],
  ["confess", "tan olish"],
  ["confuse", "aralashtiramiz"],
  ["connect", "ulanmoq"],
  ["consider", "o'ylab ko'ring"],
  ["consist", "tarkibiga kiradi"],
  ["contain", "o'z ichiga oladi"],
  ["continue", "davom eting"],
  ["copy", "nusxa ko'chirish"],
  ["correct", "to'g'ri"],
  ["cough", "yo'tal"],
  ["count", "hisoblash"],
  ["cover", "qopqoq"],
  ["crack", "yoriq"],
  ["crash", "halokat"],
  ["crawl", "ko'zdan kechirish"],
  ["cross", "kesib o'tish"],
  ["crush", "ezish"],
  ["cry", "yig'lash"],
  ["cure", "davolash"],
  ["curl", "kıvrım"],
  ["curve", "egri"],
  ["cycle", "pastadir"],
  ["dam", "to'g'on"],
  ["damage", "zarar"],
  ["dance", "raqs"],
  ["dare", "jasorat"],
  ["decay", "parchalanish"],
  ["deceive", "aldash"],
  ["decide", "qaror qabul qiling"],
  ["decorate", "bezab turing"],
  ["delay", "kechikish"],
  ["delight", "quvonch"],
  ["deliver", "etkazib berish"],
  ["depend", "bog'liq"],
  ["describe", "tasvirlab bering"],
  ["desert", "cho'l"],
  ["deserve", "haq"],
  ["destroy", "yo'q qilish"],
  ["detect", "aniqlash"],
  ["develop", "rivojlantirish"],
  ["disagree", "rozi emasman"],
  ["disappear", "yo'qoladi"],
  ["disapprove", "ma'qullamaydi"],
  ["disarm", "qurolsizlanish"],
  ["discover", "kashf qiling"],
  ["dislike", "yoqtirmaslik"],
  ["divide", "bo'lmoq"],
  ["double", "er-xotin"],
  ["doubt", "shubha"],
  ["drag", "harakatlantiring"],
  ["drain", "drenajlash"],
  ["dream", "tush"],
  ["dress", "kiyim"],
  ["drip", "tomizish"],
  ["drop", "tomchi"],
  ["drown", "cho'ktirish"],
  ["drum", "drum"],
  ["dry", "quruq"],
  ["dust", "chang"],
  ["earn", "ishlab topmoq"],
  ["educate", "tarbiyalang"],
  ["embarrass", "sharmanda qilish"],
  ["employ", "Ishlayman"],
  ["empty", "bo'sh"],
  ["encourage", "rag'batlantirish"],
  ["end", "oxiri"],
  ["enjoy", "zavqlaning"],
  ["enter", "kiriting"],
  ["entertain", "o'yin-kulgi"],
  ["escape", "qochish"],
  ["examine", "Imtihon"],
  ["excite", "qiziqish uyg'otadi"],
  ["excuse", "uzr"],
  ["exercise", "jismoniy mashqlar"],
  ["exist", "mavjud"],
  ["expand", "kengaytirish"],
  ["expect", "kuting"],
  ["explain", "tushuntirish"],
  ["explode", "portlashi mumkin"],
  ["extend", "kengaytirish"],
  ["face", "yuzi"],
  ["fade", "yo'qotish"],
  ["fail", "muvaffaqiyatsiz"],
  ["fancy", "farasingiz"],
  ["fasten", "joylashtiring"],
  ["fax", "faks"],
  ["fear", "qo'rquv"],
  ["fence", "panjara"],
  ["fetch", "olib keling"],
  ["file", "fayl"],
  ["fill", "to'ldirish"],
  ["film", "film"],
  ["fire", "olov"],
  ["fit", "muvofiq"],
  ["fix", "tuzatish"],
  ["flap", "flap"],
  ["flash", "yonib turadi"],
  ["float", "float"],
  ["flood", "suv toshqini"],
  ["flow", "oqim"],
  ["flower", "gullar"],
  ["fold", "qatlam"],
  ["follow", "amal qiling"],
  ["fool", "ahmoq"],
  ["force", "kuch"],
  ["form", "shakl"],
  ["found", "topildi"],
  ["frame", "ramka"],
  ["frighten", "qo'rqitmoq"],
  ["fry", "qovoq"],
  ["gather", "to'plash"],
  ["gaze", "qarash"],
  ["glow", "yorug'lik"],
  ["glue", "elim"],
  ["grab", "qatnashdi"],
  ["grate", "panjara qiling"],
  ["grease", "surtma"],
  ["greet", "salom"],
  ["grin", "kulrang"],
  ["grip", "tushunish"],
  ["groan", "inqirozi"],
  ["guarantee", "kafolati"],
  ["guard", "qo'riqchi"],
  ["guess", "o'ylab ko'ring"],
  ["guide", "ko'rsatma"],
  ["hammer", "bolg'a"],
  ["hand", "qo'l"],
  ["handle", "ushlab turing"],
  ["hang", "osgan"],
  ["happen", "sodir bo'lmoq"],
  ["harass", "zo'ravonlik"],
  ["harm", "zarar"],
  ["hate", "nafratlanish"],
  ["haunt", "ta'qib qilish"],
  ["head", "boshi"],
  ["heal", "shifo"],
  ["heap", "yig'ish"],
  ["heat", "issiqlik"],
  ["help", "Yordam bering"],
  ["hook", "kanca"],
  ["hop", "hop"],
  ["hope", "umid qilamiz"],
  ["hover", "hover"],
  ["hug", "quchoqlash"],
  ["hum", "chirkin"],
  ["hunt", "ov"],
  ["hurry", "shoshiling"],
  ["identify", "aniqlash"],
  ["ignore", "e'tibor bermaslik"],
  ["imagine", "tasavvur qiling"],
  ["impress", "taassurot qoldiring"],
  ["improve", "yaxshilash"],
  ["include", "ichiga oladi"],
  ["increase", "o'sish"],
  ["influence", "ta'siri"],
  ["inform", "xabar bering"],
  ["inject", "AOK qilish"],
  ["injure", "yaralash"],
  ["instruct", "ko'rsatma bering"],
  ["intend", "niyat qilish"],
  ["interest", "qiziqish"],
  ["interfere", "aralashish"],
  ["interrupt", "chiqib ketish"],
  ["introduce", "tanitish"],
  ["invent", "ixtiro qilish"],
  ["invite", "taklif qiling"],
  ["irritate", "tirnash"],
  ["itch", "qichima"],
  ["jail", "qamoqxona"],
  ["jam", "murabbo"],
  ["jog", "jog"],
  ["join", "qo'shiling"],
  ["joke", "hazil"],
  ["judge", "hukm qilish"],
  ["juggle", "juggle"],
  ["jump", "sakramoq"],
  ["kick", "kick"],
  ["kill", "o'ldirish"],
  ["kiss", "o'pish"],
  ["kneel", "tizzalari"],
  ["knit", "trikotaj"],
  ["knock", "taqillat"],
  ["knot", "tugun"],
  ["label", "yorlig'i"],
  ["land", "er"],
  ["last", "oxirgi"],
  ["laugh", "kulmoq"],
  ["launch", "ishga tushirish"],
  ["learn", "o'rganing"],
  ["level", "Daraja"],
  ["license", "litsenziya"],
  ["lick", "yalamoq"],
  ["lie", "yolg'on"],
  ["lighten", "yorug'lik"],
  ["like", "kabi"],
  ["list", "ro'yxat"],
  ["listen", "tinglang"],
  ["live", "jonli"],
  ["load", "yuk"],
  ["lock", "qulflash"],
  ["long", "uzoq"],
  ["look", "qara"],
  ["love", "sevgi"],
  ["man", "kishi"],
  ["manage", "boshqarish"],
  ["march", "marsh"],
  ["mark", "belgisi"],
  ["marry", "turmush qurish"],
  ["match", "o'yin"],
  ["mate", "turmush o'rtog'i"],
  ["matter", "modda"],
  ["measure", "o'lchov"],
  ["meddle", "aralashish"],
  ["melt", "erimaydi"],
  ["memorise", "eslab qolish"],
  ["mend", "to'ldirish"],
  ["mess up", "buzish"],
  ["milk", "sut"],
  ["mine", "meniki"],
  ["miss", "sog'indim"],
  ["mix", "aralashtiramiz"],
  ["moan", "inilti"],
  ["moor", "moor"],
  ["mourn", "qichqiraman"],
  ["move", "harakatlaning"],
  ["muddle", "zo'ravonlik"],
  ["mug", "kupa"],
  ["multiply", "ko'paytiring"],
  ["murder", "qotillik"],
  ["nail", "mix"],
  ["name", "nomi"],
  ["need", "kerak"],
  ["nest", "uy"],
  ["nod", "nod"],
  ["note", "Eslatma"],
  ["notice", "ogohlantirish"],
  ["number", "raqami"],
  ["obey", "itoat qiling"],
  ["object", "ob'ekt"],
  ["observe", "kuzating"],
  ["obtain", "olish"],
  ["occur", "paydo bo'ladi"],
  ["offend", "xafa qilish"],
  ["offer", "taklif"],
  ["open", "ochiq"],
  ["order", "buyurtma"],
  ["overflow", "toshqin"],
  ["owe", "qarzdor"],
  ["own", "Shaxsiy"],
  ["pack", "to'plami"],
  ["paddle", "paddle"],
  ["paint", "bo'yamoq"],
  ["park", "park"],
  ["part", "qism"],
  ["pass", "o'tish"],
  ["paste", "joylashtirish"],
  ["pat", "pat"],
  ["pause", "to'xtab turish"],
  ["peck", "pek"],
  ["pedal", "o'tdim"],
  ["peel", "qobig'i"],
  ["peep", "e'tibor bering"],
  ["perform", "amalga oshirish"],
  ["permit", "ruxsat berish"],
  ["phone", "telefon"],
  ["pick", "tanlash"],
  ["pinch", "qisqartirish"],
  ["pine", "qarag'ay"],
  ["place", "joy"],
  ["plan", "rejasi"],
  ["plant", "o'simlik"],
  ["play", "o'ynash"],
  ["please", "Iltimos"],
  ["plug", "vilkasi"],
  ["point", "nuqta"],
  ["poke", "poke"],
  ["polish", "polishing"],
  ["pop", "pop"],
  ["possess", "ega"],
  ["post", "post"],
  ["pour", "to'kib tashlang"],
  ["practise", "amaliyot"],
  ["pray", "ibodat qiling"],
  ["preach", "voizlik qiling"],
  ["precede", "oldin"],
  ["prefer", "afzal"],
  ["prepare", "tayyorlash"],
  ["present", "mavjud"],
  ["preserve", "himoya qilish"],
  ["press", "tugmasini bosing"],
  ["pretend", "taqlid qilish"],
  ["prevent", "oldini olish"],
  ["prick", "teshik"],
  ["print", "chop eting"],
  ["produce", "mahsulot"],
  ["program", "dasturi"],
  ["promise", "va'da"],
  ["protect", "himoya qilish"],
  ["provide", "ta'minlash"],
  ["pull", "Torting"],
  ["pump", "nasosi"],
  ["punch", "zımba"],
  ["puncture", "teshik"],
  ["punish", "jazolash"],
  ["push", "Durang"],
  ["question", "savol"],
  ["queue", "navbatda"],
  ["race", "poyga"],
  ["radiate", "radiatsiya"],
  ["rain", "yomg'ir"],
  ["raise", "oshirish"],
  ["reach", "erishish"],
  ["realise", "tushunish"],
  ["receive", "qabul qilish"],
  ["recognise", "tan oling"],
  ["record", "yozuvlar"],
  ["reduce", "kamaytirish"],
  ["reflect", "aks ettiradi"],
  ["refuse", "rad qilish"],
  ["regret", "pushaymon"],
  ["reign", "hukmronlik"],
  ["reject", "rad etish"],
  ["rejoice", "xursand bo'ling"],
  ["relax", "Rohatlaning"],
  ["release", "ozod qilish"],
  ["rely", "ishonish"],
  ["remain", "qoladi"],
  ["remember", "eslayman"],
  ["remind", "eslatib turing"],
  ["remove", "olib tashlang"],
  ["repair", "ta'mirlash"],
  ["repeat", "takrorlang"],
  ["replace", "o'zgartiring"],
  ["reply", "javob"],
  ["report", "hisobot"],
  ["reproduce", "ko'paytirish"],
  ["request", "so'rov"],
  ["rescue", "qutqarish"],
  ["retire", "nafaqaga chiqqan"],
  ["return", "qaytish"],
  ["rhyme", "qofiya"],
  ["rinse", "yuving"],
  ["risk", "xavf"],
  ["rob", "qaroqchi"],
  ["rock", "jinslar"],
  ["roll", "rulo"],
  ["rot", "rot"],
  ["rub", "rub"],
  ["ruin", "xarob"],
  ["rule", "qoidalar"],
  ["rush", "shoshilib"],
  ["sack", "xaltadan"],
  ["sail", "suzib"],
  ["satisfy", "qoniqtiramiz"],
  ["save", "saqlash"],
  ["saw", "ko'rdim"],
  ["scare", "qo'rqitish"],
  ["scatter", "tarqalishi"],
  ["scold", "sharmanda qilish"],
  ["scorch", "qovurish"],
  ["scrape", "qirib tashlash"],
  ["scratch", "chizish"],
  ["scream", "qichqiriq"],
  ["screw", "vint"],
  ["scribble", "chizish"],
  ["scrub", "ovqatlar"],
  ["seal", "muhr"],
  ["search", "qidirmoq"],
  ["separate", "alohida"],
  ["serve", "xizmat qilish"],
  ["settle", "joylashish"],
  ["shade", "soya"],
  ["share", "ulush"],
  ["shave", "sochingizni"],
  ["shelter", "boshpana"],
  ["shiver", "shivirlash"],
  ["shock", "zarba"],
  ["shop", "do'kon"],
  ["shrug", "yelka qisish"],
  ["sigh", "nafas olish"],
  ["sign", "belgisi"],
  ["signal", "signal"],
  ["sin", "gunoh"],
  ["sip", "sip"],
  ["ski", "chang'i"],
  ["skip", "atlamoq"],
  ["slap", "slap"],
  ["slip", "slip"],
  ["slow", "sekin"],
  ["smash", "sindirish"],
  ["smell", "hid"],
  ["smile", "tabassum"],
  ["smoke", "tutun"],
  ["snatch", "yopish"],
  ["sneeze", "aksirish"],
  ["sniff", "sniff"],
  ["snore", "horg'inlik"],
  ["snow", "qor"],
  ["soak", "namlanadi"],
  ["soothe", "tinchlantirish"],
  ["sound", "ovozi"],
  ["spare", "zahira"],
  ["spark", "uchqun"],
  ["sparkle", "uchqun"],
  ["spell", "spell"],
  ["spill", "to'kilmasin"],
  ["spoil", "buziladi"],
  ["spot", "spot"],
  ["spray", "buzadigan amallar"],
  ["sprout", "o'simliklar"],
  ["squash", "qovoq"],
  ["squeak", "jiqqa"],
  ["squeal", "siqilish"],
  ["squeeze", "siqish"],
  ["stain", "bo'yoq"],
  ["stamp", "muhri"],
  ["stare", "qarash"],
  ["start", "boshlang"],
  ["stay", "qolish"],
  ["steer", "boshqaring"],
  ["step", "qadam"],
  ["stir", "aralashtiramiz"],
  ["stitch", "stitch"],
  ["stop", "To'xta"],
  ["store", "saqlash"],
  ["strap", "tayoq"],
  ["strengthen", "mustahkamlash"],
  ["stretch", "cho'zish"],
  ["strip", "Ip"],
  ["stroke", "qon tomirlari"],
  ["stuff", "narsalar"],
  ["subtract", "chiqaring"],
  ["succeed", "muvaffaqiyatli"],
  ["suck", "suck"],
  ["suffer", "azoblanish"],
  ["suggest", "tavsiya qilamiz"],
  ["suit", "kostyum"],
  ["supply", "ta'minot"],
  ["support", "qo'llab-quvvatlash"],
  ["suppose", "deyman"],
  ["surprise", "ajablanib"],
  ["surround", "atrof-muhit"],
  ["suspect", "gumon qilinmoqda"],
  ["suspend", "to'xtatib turish"],
  ["switch", "switch"],
  ["talk", "gapirish"],
  ["tame", "xushbichim"],
  ["tap", "ni bosing"],
  ["taste", "ta'mi"],
  ["tease", "tease"],
  ["telephone", "telefon"],
  ["tempt", "vasvasaga solish"],
  ["terrify", "dahshat"],
  ["test", "sinov"],
  ["thank", "rahmat"],
  ["thaw", "eritish"],
  ["tick", "belgilang"],
  ["tickle", "qaynatish"],
  ["tie", "taqish"],
  ["time", "vaqt"],
  ["tip", "uchi"],
  ["tire", "buzilib ketgan"],
  ["touch", "tegish"],
  ["tour", "O'tgan"],
  ["tow", "tortish"],
  ["trace", "iz"],
  ["trade", "savdo"],
  ["train", "poezd"],
  ["transport", "transport"],
  ["trap", "tuzoq"],
  ["travel", "sayohat qilish"],
  ["treat", "davolash"],
  ["tremble", "qo'rqaman"],
  ["trick", "aldash"],
  ["trip", "sayohat"],
  ["trot", "trot"],
  ["trouble", "muammo"],
  ["trust", "ishonch"],
  ["try", "harakat qilib ko'ring"],
  ["tug", "tugma"],
  ["tumble", "tushirish"],
  ["turn", "qaytish"],
  ["twist", "twist"],
  ["type", "turi"],
  ["undress", "chirishi"],
  ["unfasten", "ochilmasin"],
  ["unite", "birlashtirish"],
  ["unlock", "qulfni ochish"],
  ["unpack", "ochish"],
  ["untidy", "tartibsiz"],
  ["use", "foydalanish"],
  ["vanish", "yo'qotish"],
  ["visit", "tashrif buyuring"],
  ["wail", "yig'layapti"],
  ["wait", "Kutmoq"],
  ["walk", "yurish"],
  ["wander", "yurish"],
  ["want", "istayman"],
  ["warm", "issiq"],
  ["warn", "ogohlantir"],
  ["wash", "yuvish"],
  ["waste", "chiqindi"],
  ["watch", "tomosha qiling"],
  ["water", "suv"],
  ["wave", "to'lqin"],
  ["weigh", "torting"],
  ["welcome", "xush kelibsiz"],
  ["whine", "xitob qildi"],
  ["whip", "qamchi"],
  ["whirl", "qichqiriq"],
  ["whisper", "pichirlash"],
  ["whistle", "hushtak"],
  ["wink", "ko'z kırpın"],
  ["wipe", "o'chirish"],
  ["wish", "istak"],
  ["wobble", "silkitardi"],
  ["wonder", "hayron"],
  ["work", "ish"],
  ["worry", "tashvishlaning"],
  ["wrap", "o'rash"],
  ["wreck", "halokat"],
  ["wrestle", "kurash"],
  ["wriggle", "chiriyotgan"],
  ["x-ray", "rentgen"],
  ["yawn", "esnamoq"],
  ["yell", "baqirmoq"],
  ["zip", "zip"],
  ["zoom", "zoom"]
]
